package com.springbootmybatis.sbm.common.model;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.money
     *
     * @mbg.generated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiverinfo
     *
     * @mbg.generated
     */
    private String receiverinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paystate
     *
     * @mbg.generated
     */
    private Integer paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbg.generated
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.money
     *
     * @return the value of orders.money
     *
     * @mbg.generated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.money
     *
     * @param money the value for orders.money
     *
     * @mbg.generated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiverinfo
     *
     * @return the value of orders.receiverinfo
     *
     * @mbg.generated
     */
    public String getReceiverinfo() {
        return receiverinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiverinfo
     *
     * @param receiverinfo the value for orders.receiverinfo
     *
     * @mbg.generated
     */
    public void setReceiverinfo(String receiverinfo) {
        this.receiverinfo = receiverinfo == null ? null : receiverinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paystate
     *
     * @return the value of orders.paystate
     *
     * @mbg.generated
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paystate
     *
     * @param paystate the value for orders.paystate
     *
     * @mbg.generated
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbg.generated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbg.generated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orders other = (Orders) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getReceiverinfo() == null ? other.getReceiverinfo() == null : this.getReceiverinfo().equals(other.getReceiverinfo()))
            && (this.getPaystate() == null ? other.getPaystate() == null : this.getPaystate().equals(other.getPaystate()))
            && (this.getOrdertime() == null ? other.getOrdertime() == null : this.getOrdertime().equals(other.getOrdertime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getReceiverinfo() == null) ? 0 : getReceiverinfo().hashCode());
        result = prime * result + ((getPaystate() == null) ? 0 : getPaystate().hashCode());
        result = prime * result + ((getOrdertime() == null) ? 0 : getOrdertime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", money=").append(money);
        sb.append(", receiverinfo=").append(receiverinfo);
        sb.append(", paystate=").append(paystate);
        sb.append(", ordertime=").append(ordertime);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}